IdeaHub/IdeaHub/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('userprofile.urls')),
    path('', include('thehub.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IdeaHub/thehub/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    # Path to the project profile view
    path("thehub/project/<str:project_name>/", views.project, name="project"),
    # The path without the post_id is used for prefilled the html when the page is rendered. It does not have a function
    path("thehub/post/", views.makePost, name="makePost"),
    path("thehub/post/<str:project_name>/", views.makePost, name="makePost"),
    path("thehub/post/<str:project_name>/<int:parent_post_id>", views.makePost, name="makePost"),
    # Path me make a respond, used by AJAX
    path("thehub/respond/", views.makeRespond, name="makeRespond"),
    path("thehub/respond/<str:project_name>/<int:parent_post_id>", views.makeRespond, name="makeRespond"),

    # The path without post_id is used to make sure template can be rendered without error
    path("thehub/getprojectupdate/<str:project_name>/<int:post_id>", views.getProjectUpdate, name="ajaxProjectUpdate"),
    path("thehub/getprojectupdate/<str:project_name>/", views.getProjectUpdate, name="ajaxProjectUpdate"),
    path("thehub/getuserupdate/<str:username>/<int:post_id>", views.getUserUpdate, name="ajaxUserUpdate"),
    path("thehub/getuserupdate/<str:username>/", views.getUserUpdate, name="ajaxUserUpdate"),
    # Filter by category
    path("thehub/filterByCategory/<str:category>/", views.filterProjectByCategory, name="filterByCategory"),
    # Search projects with given keywords, the empty parameter url is for initial rendering the page
    path("thehub/search/<str:keywords>/", views.searchProjectsByKeywords, name="searchProjects"),
    path("thehub/search/", views.searchProjectsByKeywords, name="searchProjects"),
    # Subscribe or unsubscribe url
    path("thehub/subscription/<str:project_name>/", views.manageSubscription, name="manageSubscription"),
    # Ask to join or leave as member
    path("thehub/memberrequest/<str:project_name>/", views.manageMemberRequest, name="memberrequest"),
    path("thehub/memberrequest/<int:member_request_id>/<str:result>", views.approveDeclineMemberRequest, name="approveDeclineMemberRequest"),

    # Create new project
    path("thehub/new_project/", login_required(views.CreateProject.as_view(), login_url="login"), name="createProject"),
    # Delete a project
    path("thehub/delete_project/<str:project_name>", views.deleteProject, name="deleteProject"),
]

IdeaHub/thehub/models.py
from django.db import models
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist


# Create your models here.
class ProjectManager(models.Manager):
    """
    The custom manager to provide higher level API for the Project objects
    """
    def get_all_projects(self):
        """
        Get all projects in the database
        """
        return self.all()

    def get_project_of_user(self, username):
        """
        Get all projects (members and owner) of the given user
        """
        return (self.filter(members__username__iexact=username)
                | self.filter(owner__username__iexact=username)).distinct()

    def get_project_owned_by(self, username):
        """
        Get all projects that the given user owned
        """
        return self.filter(owner__username__iexact=username)

    def get_project_subscribed_by(self, username):
        """
        Get all projects that the given user subscribed
        """
        return self.filter(subscribers__username__iexact=username).distinct()

    def get_projects_user_interested(self, username):
        """
        Get all projects that the given username is owned, member, or subscribed.
        """
        return self.get_project_of_user(username) | self.get_project_subscribed_by(username)

    def get_project_by_name(self, project_name):
        """
        Get the project using name (return a single project, not a query set)

        Raise: Http404 if not found
        """
        try:
            project = self.get(project_name=project_name)
            return project
        except ObjectDoesNotExist:
            raise Http404("There is no project with the given name in database")

    def get_all_categories(self):
        """
        Get all categories in the database
        """
        categories = []
        for category in Project.CATEGORIES:
            categories.append(category[0])
        return categories
    
    def get_projects_by_category(self, category):
        """
        Get all projects in the given category
        """
        return self.filter(category__iexact=category).distinct()

class Project(models.Model):
    """
    The model for project object
    """
    # Basic information of Project
    project_name = models.CharField(max_length=150, blank=False, primary_key=True)
    description = models.TextField(max_length=None, blank=False)
    created_date = models.DateTimeField(verbose_name="Created date", auto_now_add=True)
    # Category
    CATEGORIES = (("Designing", "Designing"),
                    ("Coding", "Coding"),
                    ("Cooking", "Cooking"),
                    ("Photography", "Photography"),
                    ("Writing", "Writing"),
                    ("Traveling", "Traveling"),
                    ("Other", "Other"))
    category = models.CharField(choices=CATEGORIES, default="Other", max_length=20, blank=False)

    # The owner is the person who creatde the project, whereas the members are ones participating in the project
    owner = models.ForeignKey("userprofile.MyUser", on_delete=models.CASCADE)
    # The owner should NOT be added as member
    members = models.ManyToManyField("userprofile.MyUser", related_name="projects")
    # The list of subscribers of this project, subcribers will only have the option of normal user but will get update as well
    # NOTICE: this list does not contains members and owner
    subscribers = models.ManyToManyField("userprofile.MyUser", related_name="subscriptions")

    # Set the manager of this model
    objects = ProjectManager()

    def __str__(self):
        return self.project_name

# ============================================================================================
class PostManager(models.Manager):
    """
    The custom manager to manage the database of Post
    """
    def get_posts_of_user(self, username):
        """
        Method to get all the posts of the given usename
        """
        return self.filter(user__username__iexact=username).distinct()

    def get_post_user_intested(self, username):
        """
        Method to get all the posts from projects that the user is owner/member/subscribed.

        Return: QuerySet contains all posts that user should see, distinct.
        """
        projects = Project.objects.get_projects_user_interested(username)
        
        posts = None
        for project in projects:
            if posts is None:
                posts = self.get_all_posts_of_project(project.project_name)
            else:
                # Unify the current set with the new query set
                posts = posts | self.get_all_posts_of_project(project.project_name)

        return posts.distinct() if posts else None

    def get_parent_posts_user_interested(self, username):
        """
        Method to get all the parent posts that user should see. The children post can be found based on this in views code
        """
        projects = Project.objects.get_projects_user_interested(username)

        posts = None
        for project in projects:
            if posts is None:
                posts = self.get_all_posts_of_project(project.project_name).filter(parent__isnull=True)
            else:
                # Unify the current set with the new query set
                posts = posts | self.get_all_posts_of_project(project.project_name).filter(parent__isnull=True)

        return posts.distinct() if posts else None


    def get_parent_posts_of_project(self, project_name):
        """
        Method to get all the post that are parents(direct comment) of the given project
        """
        # This query all posts that do not have parent (they are the root)
        return self.filter(project__project_name__iexact=project_name).filter(parent__isnull=True).distinct()

    def get_chilren_of_post(self, post_id):
        """
        Method to get all the children of a given post (response to that post)
        """
        return self.filter(parent__id__iexact=post_id).distinct()
    
    def get_all_posts_of_project(self, project_name):
        """
        Method to get all the post of the given project
        """
        return self.filter(project__project_name__iexact=project_name).distinct()


class Post(models.Model):
    """
    The model for a post. A post can be a comment, a question, or an update on the current project
    """

    TYPES = (("Q", "Question"), ("C", "Comment"), ("U", "Update"))

    # Not allowed post without content
    content = models.TextField(blank=False)
    type = models.CharField(choices=TYPES, blank=False, default="C", max_length=2)
    # Auto assigned the created time
    time_posted = models.DateTimeField(auto_now_add=True)

    # TODO: A parent post can have many child comments/
    parent = models.ForeignKey("Post", on_delete=models.CASCADE, blank=True, null=True)

    # The user and project this post belongs to
    user = models.ForeignKey("userprofile.MyUser", on_delete=models.CASCADE)
    project = models.ForeignKey("Project", on_delete=models.CASCADE)

    # Custom manager
    objects = PostManager()

    def __str__(self):
        return self.content


# ============================================================================================

class MemberRequestManager(models.Manager):
    """
    Custom mamanger for the member request model
    """
    # ============================================================================================

    def create_request(self, project, user):
        """
        Creating a new request in the database
        """
        request = self.create(project=project, user=user)
        return request

    def get_requests_for_project(self, project):
        return self.filter(project__exact=project)


class MemberRequest(models.Model):
    """
    The model for requesting to join as a member for a project.
    """
    
    project = models.ForeignKey("Project", on_delete=models.CASCADE, blank=False)
    user = models.ForeignKey("userprofile.MyUser", on_delete=models.CASCADE)

    objects = MemberRequestManager()

    def __str__(self):
        return "{} has asked to join {}".format(self.user, self.project)

IdeaHub/thehub/forms.py
from django import forms
from .models import Post
from .models import Project

class MemberPostForm(forms.ModelForm):
    """
    Form to create a new post for a project as a member. This post is parent-level postself.
    There will be the option to post as update.
    All information of user and project should be populated by the view's backend code
    """
    class Meta:
        model = Post
        # In all cases, project should be prefilled by view's backend code
        fields = ["content", "type"]


class GeneralPostForm(forms.ModelForm):
    """
    Form to create a post for general user, this only include the option to post as comment or question, not update post.
    """
    class Meta:
        model = Post
        # Project should be prefilled by view's backend code
        fields = ["content", "type"]
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["type"].choices = (("Q", "Question"), ("C", "Comment"))
    
class ProjectForm(forms.ModelForm):
    """
    Form to create a new project for a project as a member.
    """
    class Meta:
        model = Project
        fields = [
            "project_name", "description", "category"
        ]

IdeaHub/templates/thehub/home.html
{% extends 'base.html' %}

{% block title %}
Idea Hub
{% endblock %}

{% block content %}
<div class="container">
  <!-- Categories -->
  <div class='wrapper text-center mb-3'>
    <div class="btn-group">
        <a class="category btn btn-link mr-4 text-success"  href="{% url 'filterByCategory' 'All' %}">All</a>
      {% for category in categories %}
        <a class="category btn btn-link mr-4 text-success" href="{% url 'filterByCategory' category %}">{{ category }}</a>
      {% endfor %}
    </div>
  </div>
  <hr style="border-color: rgb(70, 113, 192);">
  <!-- Projects -->
  <div class="row">
    {% for project in all_projects %}
      <div class="col-sm-4 py-2">
        <div class="card card-body h-100" style="border-color:#97D67E;">
          <a style="color: rgb(70, 113, 192); font-size: 1.25em; font-weight: bold;" href="{% url 'project' project.project_name %}" class="card-title mb-1">{{ project.project_name }}</a>
          <h6 class="card-subtitle mb-2 text-muted">{{ project.owner }}</h6>
          <p class="card-text">{{ project.description }}</p>
        </div>
      </div>
    {% endfor %}
  </div>
</div>
{% endblock %}
{% block javascripts %}
<script>

  $(".category").click(function(event){
      filterByCategoryAjax(event, $(this).attr("href"));
    });

	function filterByCategoryAjax(event, category_href) {
    event.preventDefault();
		$.ajax({
			url: category_href,
			success: function (data) {
				// console.log(data);
				data = JSON.parse(data);
        $(".row").empty();
			
        // Loop over the data and update the front-end if needed.
				for (let i = 0; i < data.length; i++) {
          const project = data[i];
          var newProjectView = document.createElement("div");
          newProjectView.setAttribute("class", "col-sm-4 py-2");
          newProjectView.innerHTML = "<div class='card card-body h-100' style='border-color:#97D67E;'> <a style='color: rgb(70, 113, 192); font-size: 1.25em; font-weight: bold;' href='" + project.url + "' class='card-title mb-1'>" + project.project_name + "</a><h6 class='card-subtitle mb-2 text-muted'>" + project.owner + "</h6><p class='card-text'>" + project.description + "</p></div>";
          $(".row").append(newProjectView);
        }
			},
			complete: function () {
				
			}
		});
	};
</script>
{% endblock %}

IdeaHub/templates/thehub/project-profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
{{project.project_name}}
{% endblock %}

{% block content %}
<div class="row">
	<div class="project-banner">{{project.project_name}}</div>
</div>
<div class="row">
	<div class="column left">
		<div class="profile-info">
			<h6>About the project: </h6>
			<p>{{project.description}}</p>
			<h6>Category: </h6>
			<p>{{project.category}}</p>
			<h6>Project owner: </h6>
			<p>{{project.owner.first_name}} {{project.owner.last_name}}</p>
		</div>
		<div class="project-actions">
			<a id="make-post" class="btn btn-warning">Make post</a>
			{% if project not in projects and project not in subscriptions %}
				{% if project not in pending_projects %}
					<a class="btn btn-primary" href="{% url 'memberrequest' project.project_name %}">Ask to join</a>
				{% endif %}
				<a class="btn btn-info" href="{% url 'manageSubscription' project.project_name %}">Subscribe</a>
			{% elif project in subscriptions %}
				{% if project not in pending_projects %}
					<a class="btn btn-primary" href="{% url 'memberrequest' project.project_name %}">Ask to join</a>
				{% endif %}
				<a class="btn btn-info" href="{% url 'manageSubscription' project.project_name %}">Unsubscribe</a>
			{% elif project in projects %}
				{% if project in owned_projects %}
					<a class="btn btn-danger" href="{% url 'deleteProject' project.project_name %}">Delete project</a>
				{% else %}
					<a class="btn btn-primary" href="{% url 'memberrequest' project.project_name %}">Leave project</a>
				{% endif %}
			{% endif %}
		</div>
	</div>
	<div id="list_posts" class="column right">
		{% for post in posts %}
		<div id="{{post.id}}" class="entry">
			<p>
				<span style="font-weight:bold; color:tomato">{{post.user.username}}</span>
				<span style="font-weight:bold">{{post.get_type_display}}:</span>
				{{post.content}}
			</p>
			{% for id, child in children_posts.items %}
				{% ifequal id post.pk %}
					{% for child_post in child %}
					<div id="{{child_post.id}}" class="response">
						<p>
							<span style="font-weight:bold; color:tomato">{{child_post.user.username}}:</span>
							{{child_post.content}}
						</p>
					</div>
					{% endfor %}
				{% endifequal %}
			{% endfor %}
			<!-- TODO: WHENEVER updated the code for reponse button here, update the ajax code as well. -->
			<button type="button" class="btn btn-primary respond-button">Respond</button>
		</div>
		{% endfor %}
	</div>
</div>

<div id="modalDisplay" class="modal">
</div>

{% endblock %}
{% block javascripts %}
<script>
	$("#make-post").click(function (event) {
		event.preventDefault();
		var innerHTMLstr = "<div class='modal-content'><span class='close'>&times;</span></br><form action='" + "{% url 'makePost' project.project_name %}" + "' method='post'><div class='form-group'><label for='type'>Type:</label><select class='form-control' id='type' type='text' name='type'> <option value='C'>Comment</option><option value='Q'>Question</option> {% ifequal canUpdate True %} <option value='U'>Update</option> {% endifequal %} </select></div><div class='form-group'> <label for='content'>Message:</label><textarea name='content' id='content' class='form-control' rows='3'></textarea></div><div class='form-group'></div><input type='submit' class='btn btn-success float-right' value='Post'></input><button style='margin-right:5px' class='cancel btn btn-danger float-right'>Cancel</button>";
		var csfr = "<input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}'></form></div>";
		$("#modalDisplay").html(innerHTMLstr + csfr);
		$(".cancel").click(function (event) {
			event.preventDefault();
			$("#modalDisplay").hide();
		});
		$(".close").click(function () {
			$("#modalDisplay").hide();
		});
		$("#modalDisplay").show();
	});

	function clickRespond(event) {
		event.preventDefault();
		var innerHTMLstr = "<div class='modal-content'><span class='close'>&times;</span></br><form action='" + "{% url 'makePost' project.project_name %}" + $(event.target).parent().attr('id') + "' method='post'><div class='form-group'> <label for='content'>Message:</label><textarea name='content' id='content' class='form-control' rows='3'></textarea></div><div class='form-group'><input name='type' style='display: none' value='C'></div><input type='submit' class='btn btn-success float-right' value='Post'></input><button style='margin-right:5px' class='cancel btn btn-danger float-right'>Cancel</button>";
		var csfr = "<input type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}'></form></div>";
		$("#modalDisplay").html(innerHTMLstr + csfr);
		$(".cancel").click(function (event) {
			event.preventDefault();
			$("#modalDisplay").hide();
		});
		$(".close").click(function () {
			$("#modalDisplay").hide();
		});
		$("#modalDisplay").show();
	}
	$(".respond-button").click(clickRespond);


	function getProjectUpdateAjax() {
		var posts = $(".entry, .response");
		var ids = [];

		for (let index = 0; index < posts.length; index++) {
			const post = posts[index];
			ids.push(Number($(post).attr("id")));
		}
		var max_id = Math.max(...ids);

		$.ajax({
			url: "{% url 'ajaxProjectUpdate' project.project_name %}" + max_id,
			success: function (data) {
				console.log(data);
				data = JSON.parse(data);

				// Loop over the data and update the front-end if needed.
				for (let index = 0; index < data.length; index++) {
					const post = data[index];

					var newPostDiv = document.createElement("div");
					newPostDiv.setAttribute("id", Number(post["id"]).toString());

					var content = document.createElement("p");
					if (post["parent"] == "") {
						// This is a parent post
						content.innerHTML = "<span style='font-weight: bold; color: tomato'>" + post["user"] + "</span> " + "<span style='font-weight: bold'>" + post["type"] + ":</span>" + post["content"];
					} else {
						content.innerHTML = "<span style='font-weight: bold; color: tomato'>" + post["user"] + ":</span> " + post["content"];
					}
					newPostDiv.appendChild(content);

					if (post["parent"] == "") {
						// This is a parent post
						newPostDiv.setAttribute("class", "entry");
						// A parent post should include the reponse button as well
						var responseButton = document.createElement("button");
						responseButton.setAttribute("type", "button");
						responseButton.setAttribute("class", "btn btn-primary respond-button");
						responseButton.textContent = "Respond";
						$(responseButton).click(clickRespond);

						newPostDiv.appendChild(responseButton);
						$("#list_posts").prepend(newPostDiv);
					} else {
						// This is a response post
						newPostDiv.setAttribute("class", "response");
						// This post need to be under its parent, but BEFORE the respond button
						// THe space in front of button needs to be there because it is CSS selector #id button:lastchild
						var responseButton = $("#" + Number(post["parent"]).toString() + " button:last-child");

						var childSelector = "#" + Number(post["parent"]).toString();
						$(newPostDiv).insertBefore(responseButton);
					}
				}
			},
			complete: function () {
				setTimeout(getProjectUpdateAjax, 2000);
			}
		});
	}
	$(document).ready(function () {
		setTimeout(getProjectUpdateAjax, 2000);
	});
</script>
<script type="text/javascript" src="{% static 'thehub/pop-ups.js' %}"></script>
{% endblock %}

IdeaHub/templates/thehub/project_form.html
{% extends 'base.html' %}

{% block title %}
Create new project
{% endblock %}

{% block content %}
<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <span class="border rounded border-secondary p-5 mr-7" style="background-color: white">
        <h3 class="d-flex justify-content-center p-2">Create New Project</h3>
        <form action="{% url 'createProject' %}" method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-outline-primary float-right">Submit</button>
        </form>
        </span>
    </div>
</div>
{% endblock %}
{% block javascripts %}
<script>
        var formGroups = $('p');
        for(let i=0; i < formGroups.length; i++) {
            var ele = formGroups[i];
            $(ele).replaceWith("<div class='form-group'>" + $(ele).html() + "</div>");
        }
        $('select').addClass("custom-select custom-selct-lg");
        $('textarea').addClass("form-control");
        $('input').addClass("form-control");
    
        $('li').addClass("text-muted");
        $('.helptext').addClass("text-muted");
    
        $('.errorlist li').removeClass("text-muted");
        $(".errorlist li").attr("style", "color:red");
    
    </script>
{% endblock %}